# Generated by Django 4.1.7 on 2023-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0004_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
