# Generated by Django 4.1.7 on 2023-05-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0006_review"),
    ]

    operations = [
        migrations.RemoveField(model_name="menuitem", name="quantity",),
    ]
